MSBUILD DEMO ADAPTER - NOT VC6 QUALIFICATION
TEAM_BOB_MSBUILD_DEMO_PROTOCOL_V1_NOT_VC6
NOT A VISUAL C++ 6 PROJECT
# ì˙ñ{åÍ: Ç±ÇÍÇÕ VC6 project Ç≈ÇÕÇ»Ç≠ÅAå¿íË adapter protocol ÇÃ token Ç≈Ç∑ÅB
PROJECT_BASENAME=CycleWatch
CONFIGURATION=Release
PLATFORM=Win32
